language: python
python:
  - "3.5"
  - "3.4"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils
install:
  - make build
  - pip install -r test_requirements.txt
  - pip install codecov
script:
  - pytest -v tests/ --cov=transform --cov-report html
after_success:
  - codecov
